### PR TITLE
Import db

### PR DESCRIPTION
**Pull request by dmarin**
This is to import a database from a file

### CODE REVIEW

**Comment by reisub** [comment]
Hi @dmarin,
thanks for taking the time to contribute new features!

The code looks good, you matched the style well. The only thing lint complains about is the name for the resource `ic_file_download_white_24dp.png`. It need to start with `dbinspector_` so we don't accidentally clash with resources in the rest of the project. Can you fix that?

More generally, the Travis build will fail if `./gradlew check` fails so you can also run it locally if you don't want to wait for Travis.

**Comment by reisub** [comment]
Also, now that I think about it - that icon should probably be an icon pointing up as in upload, import. Down makes me thing download, export.

**Comment by dmarin** [comment]
Hi @reisub 

Thanks, I did not know about the ./gradlew check. I have done a new commit with the requested changes.
Thanks again for this library

**Comment by reisub** [comment]
Thanks!

**Comment by reisub** [comment]
This morning we released DbInspector `3.2.0` to maven which includes this feature. It might take a while for it to show up in search on maven central, but you can start using it within the hour.

**Pull request merged**
