### PR TITLE
Show external database

### PR DESCRIPTION
**Pull request by Aexyn**
This is working for me..

### CODE REVIEW

**Comment by reisub** [comment]
Hi @Aexyn, thanks for taking the time to do a PR.

The code looks good, but there is a couple of other issues:
1. It looks like you did the PR with some changes from @zplesac which are not yet ready to be merged in master. Please make a PR with your changes only.
2. The travis build fails because you bumped the android sdk and build tools version. Please also update the `.travis.yml` (components section) file so the build passes. (https://travis-ci.org/infinum/android_dbinspector/builds/62514741)

Can you make a new PR with these changes?

**Comment by Aexyn** [comment]
I can try.. But I dont know how @zplesac changes got merged. I just forked the master

**Comment by Aexyn** [comment]
Again pull requested

**Comment by Aexyn** [comment]
Build failed Again.. I dont know why

**Pull request closed without merging**
