### PR TITLE
Fix issue #32

### LINKED ISSUE #32: Build error after updating Android support libs to v23.2
Using
```
compile 'com.android.support:support-v4:23.2.0'
compile 'com.android.support:appcompat-v7:23.2.0'
```
along with
`debugCompile 'im.dino:dbinspector:3.2.2@aar'`

results in the build error:
```
:app:processDebugResources
/Users/dino/android/dbinspector/dbinspector/src/main/res/menu/dbinspector_fragment_table_list.xml:13: AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/abc_ic_menu_copy_mtrl_am_alpha').
/Users/dino/android/dbinspector/dbinspector/src/main/res/menu/dbinspector_fragment_table_list.xml:21: AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/abc_ic_menu_share_mtrl_alpha').

 FAILED
```

If I revert back to `23.1.1` for the support libs, the issue goes away.

### PR DESCRIPTION
**Pull request by MarcBernstein**
Copied over resources from support lib 23.2 locally to the project.

Fixes #32.

### CODE REVIEW

**Comment by reisub** [comment]
Hey Marc, thanks for your contribution!
Travis is complaining because we have lint setup so it complains if the resources aren't prefixed with dbinspector_ which is great in this case because we don't want to clash with support lib older than 23.2.0.

Sorry I forgot to mention it before, but could you just rename the drawables and maybe give them a bit better names too?
Something like `dbinspector_copy`.

**Comment by MarcBernstein** [comment]
You got it. I'll update the branch shortly.

**Comment by reisub** [comment]
Thanks Marc, great work!

**Comment by reisub** [comment]
Version 3.2.3 was released to maven central and should be available in the next hour or so.

**Pull request merged**
