### PR TITLE
Enhancement querier

### PR DESCRIPTION
**Pull request by javierjmc**
Adding table queries. 

Kudos to Željko Plesac for providing initial work on this enhancement.

### CODE REVIEW

**Comment by reisub** [comment]
Hi @javierjmc,

thanks for the effort! Travis is complaining because `.travis.yml` also needs to install the correct build tools (`25.0.1` in this case).

**Comment by zplesac** [comment]
@javierjmc great work, this is really awesome!

**Comment by reisub** [comment]
Looks good to me, thanks again for doing the work!
I'm merging this in and we'll include it in the next release once we test it and fix any bugs that come up.

**Comment by javierjmc** [comment]
Great, thanks @reisub!

**Pull request merged**
